language: php

sudo: required

cache:
  directories:
    node_modules

php:
  - 7.1

git:
  depth: 1

matrix:
  include:
    - language: node_js
      node_js:
        - 6
    - language: php
      php:
        - 7.1

install:
  - travis_retry curl -s http://getcomposer.org/installer | php
  - travis_retry php composer.phar install --no-interaction
  
scripts:
  - mkdir -p tests/logs
  - php vendor/bin/phpunit