language: php

sudo: required

cache:
  directories:
    node_modules

php:
  - 7.1

node_js:
  - 6

git:
  depth: 1

matrix:
  include:
    - dist: precise
      php: 7.1
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - travis_retry curl -s http://getcomposer.org/installer | php
  - travis_retry php composer.phar install --no-interaction
  
scripts:
  - mkdir -p tests/logs
  - php vendor/bin/phpunit